server:
  port: 8080

spring:
  cloud:
    gateway:
      # --- All keys are now prefixed with 'server.webflux' ---
      server:
        webflux:
          routes:
            - id: device-service-route
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/deviceservice/**


          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
