server:
  port: 8080

# --- Central Swagger UI Configuration ---
springdoc:
  swagger-ui:
    # This is the new, single, central URL
    path: /swagger-ui.html
  # This tells the gateway to find API definitions
  # from services in Eureka
  discovery:
    enabled: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # --- ROUTE 1: Your manual route for the device service ---
            - id: device-service-route
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/deviceservice/**
              filters:
                # This removes /deviceservice before forwarding
                # to the device-service (which is correct)
                - StripPrefix=1
                
      # This locator finds all other services (like Eureka)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
              
management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
