server:
  port: 8080

# --- Central Swagger UI Configuration ---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # This manually creates the dropdown menu
    urls:
      - name: Device Service
        url: /v3/api-docs/device-service

spring:
  cloud:
    gateway:
      server:
        webflux:
          
          # --- All routes go here ---
          routes:
            # --- ROUTE 1: Your manual route for the device service ---
            - id: device-service-route
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/deviceservice/**
              filters:
                - StripPrefix=1
                
            # --- ROUTE 2: THE ROUTE FOR SWAGGER (WITH THE FIX) ---
            - id: openapi-dynamic-route
              uri: lb://{segment}
              predicates:
                # Captures 'device-service' as 'segment'
                - Path=/v3/api-docs/{segment}
              filters:
                # --- THIS IS THE FIX ---
                # This simpler filter just rewrites the path and doesn't conflict
                - RewritePath=/v3/api-docs/.*, /v3/api-docs
          
          # --- This block fixes the deprecation warning ---
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              
management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
