server:
  port: 8080 

spring:
  cloud:
    gateway:
      discovery:
        locator:
          # This tells the gateway to use Eureka to find other services
          enabled: true 
          lower-case-service-id: true
