server:
  port: 8080

# --- Central Swagger UI Configuration ---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # This manually creates the dropdown menu
    urls:
      - name: Device Service
        url: /v3/api-docs/device-service
      - name: License Service
        url: /v3/api-docs/license-service

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # --- DEVICE-SERVICE ROUTES ---
            - id: device-service-route
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/deviceservice/**
              filters:
                - StripPrefix=1
                
            - id: openapi-deviceservice-route
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/v3/api-docs/device-service
              filters:
                - RewritePath=/v3/api-docs/device-service, /v3/api-docs

            # --- LICENSE-SERVICE ROUTES ---
            - id: license-service-route
              uri: lb://LICENSE-SERVICE
              predicates:
                - Path=/licenseservice/**
              filters:
                - StripPrefix=1

            - id: openapi-licenseservice-route
              uri: lb://LICENSE-SERVICE
              predicates:
                - Path=/v3/api-docs/license-service
              filters:
                - RewritePath=/v3/api-docs/license-service, /v3/api-docs
          
          # --- This block fixes the deprecation warning ---
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              
management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
