server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Device Service
        url: /v3/api-docs/device-service
      - name: License Service
        url: /v3/api-docs/license-service
      - name: User Service
        url: /v3/api-docs/user-service
    use-relative-path: true

spring:
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

    gateway:
      routes:

        - id: device-service-route
          uri: lb://DEVICE-SERVICE
          predicates:
            - Path=/deviceservice/**
          filters:
            - StripPrefix=1

        - id: openapi-deviceservice-route
          uri: lb://DEVICE-SERVICE
          predicates:
            - Path=/v3/api-docs/device-service
          filters:
            - RewritePath=/v3/api-docs/device-service, /v3/api-docs

        - id: license-service-route
          uri: lb://LICENSE-SERVICE
          predicates:
            - Path=/licenseservice/**
          filters:
            - StripPrefix=1

        - id: openapi-licenseservice-route
          uri: lb://LICENSE-SERVICE
          predicates:
            - Path=/v3/api-docs/license-service
          filters:
            - RewritePath=/v3/api-docs/license-service, /v3/api-docs

        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/userservice/**
          filters:
            - StripPrefix=1

        - id: openapi-userservice-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
    non-secure-port: ${server.port}
