server:
  port: 8080

# --- Central Swagger UI Configuration ---
springdoc:
  swagger-ui:
    # This is the new, single, central URL
    path: /swagger-ui.html
  # This tells the gateway to find API definitions
  # from services in Eureka
  discovery:
    enabled: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # --- ROUTE 1: Your manual route for the device service ---
            - id: device-service-route
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/deviceservice/**
              filters:
                # This removes /deviceservice before forwarding
                - StripPrefix=1
                
            # --- ROUTE 2: THE MISSING ROUTE FOR SWAGGER ---
            # This route finds the /v3/api-docs endpoint on any service
            # registered with Eureka (like 'device-service')
            - id: openapi-dynamic-route
              # 'lb' means use Eureka. The 'segment' variable is
              # captured from the predicate below.
              uri: lb://{segment}
              predicates:
                # This captures the service name (e.g., "device-service")
                # from the URL into a variable named 'segment'
                - Path=/v3/api-docs/{segment}
              filters:
                # This rewrites the path before forwarding it.
                # from: /v3/api-docs/device-service
                # to:   /v3/api-docs
                - RewritePath=/v3/api-docs/(?<segment>.*), /v3/api-docs

      # This locator finds all other services (we can leave it)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
              
management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
