server:
  port: 8080

# This section enables the central Swagger page ON THE GATEWAY
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    # This is the new, single, central URL
    path: /swagger-ui.html
  # This tells the gateway to look for APIs in Eureka
  discovery:
    enabled: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # This is your device-service route
            - id: device-service-route
              uri: lb://DEVICE-SERVICE
              predicates:
                - Path=/deviceservice/**
              filters:
                # --- THIS IS NOW CORRECTLY ADDED BACK ---
                - StripPrefix=1
          
          # This tells the gateway how to find all microservices
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              
management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
