server:
  port: 8080 

spring:
  cloud:
    gateway:
      discovery:
        locator:
          
          enabled: true
          lower-case-service-id: true


management:
  endpoints:
    web:
      exposure:
        
        include: health,info

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
