server:
  port: 9004

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info

# --- Custom Application Properties ---
app:
  clients:
    user-service:
      url: "lb://user-service/api/v1/users"
    
    audit-service:
      url: "lb://audit-service/api/v1/audit"

  jwt:
    expiration-ms: 3600000 # 1 hour

springdoc:
  servers:
    - url: /auth
      description: Auth Service via Gateway
