server:
  port: 9004

spring:
  security:
    oauth2:
      authorizationserver:
        # This value will appear as the "issuer" claim in every JWT
        issuer: http://localhost:9004

# --- Eureka Client Configuration ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    secure-port-enabled: false
    non-secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health

# --- Actuator Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: health,info

# --- Custom Application Properties ---
app:
  clients:
    user-service:
      # WebClient base URL for user-service, load-balanced via Eureka
      url: "lb://user-service/api/v1/users"

    audit-service:
      # New: WebClient base URL for audit-service
      # Used for sending login/password change audit logs
      url: "lb://audit-service"

  jwt:
    # JWT expiration time in milliseconds
    expiration-ms: 3600000 # 1 hour
    
  internal-auth-key: ${INTERNAL_AUTH_KEY}

springdoc:
  servers:
    - url: /auth
      description: Auth Service via Gateway
